---
- name: Deploy Yolo Application and DB
  hosts: all
  tasks:
    # - name: Clone Repository from Github
    #   git:
    #     repo: https://github.com/omondijeff/yolo
    #     dest: /repo-clone
    - name: Build Docker Image for Client
      import_tasks: roles/client/tasks/client.yml
      #validate_certs: false

    - name: Install Docker
      package:
        name: docker-ce
        state: present

    - name: Build Docker Image for Backend
      import_tasks: roles/backend/tasks/backend.yml
      #validate_certs: false
    # roles:
    #   - client
    # vars:
    #   group: webservers

- name: Run MongoDB container
  hosts: dbservers
  tasks:
    - name: Create MongoDB Volume
      docker_volume:
        name: mongo_data
        driver: local
      #validate_certs: false
    - name: Run MongoDB container
      import_tasks:
        roles/mongo/tasks/main.yml
        # roles:
        #   - mongo
