---
# Install Docker
# --
#
- name: install prerequisites
  apt:
    name:
      - docker.io
    update_cache: yes

- name: add user permissions
  shell: "usermod -aG docker vmadmin"

- name: Reset ssh connection for changes to take effect
  meta: "reset_connection"

# Installs Docker SDK
# --
#
- name: install python package manager
  apt:
    name: python3-pip

- name: install python sdk
  become_user: vmadmin
  pip:
    name:
      - docker
      - docker-compose
