---
- name: Build client image
  docker_image:
    path: /roles/client
    name: yolo_client
    state: present
    

- name: Run client container
  docker_container:
    name: yolo_client
    image: yolo_client
    ports:
      - "3000:3000"
    volumes:
      - /roles/client:/app
    state: present
